version: "3.9"

services:
  db:
    image: postgres
    container_name: db_shop
    volumes:
      - db_shop_vol:/var/lib/postgresql/data
    env_file:
      - .env.dev
    ports:
      - 5432:5432

  webapp:
    restart: always
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"

volumes:
  db_shop_vol: